name: 'Automatic build'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  run-myscript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: |
          ./tools/create_pkg_repo.sh http://192.168.157.172/deb gh-pages "GitHub Actions" "41898282+github-actions[bot]@users.noreply.github.com"

